### ISSUE TITLE
"CleanSum" summary contains null for "totalTime" and "totalTimeFormatted" (T9)

### ISSUE THREAD

**Issue by unclej84** [mrbungle64/node-red-contrib-ecovacs-deebot#13] opened 2021-05-01 14:27 UTC
When running command `GetCleanSum` 4 messages are returned - `totalSquareMeters`, `totalSeconds`, `totalNumber` and a summary. The summary contains the correct values from the other 3 messages but `totalTime` and `totalTimeFormatted` are `null`.

**Comment by mrbungle64** [comment] 2021-05-01 15:44
@unclej84 

I can confirm that (OZMO 920)

**Comment by mrbungle64** [comment] 2021-05-01 19:21
@unclej84 

I removed `totalTime` and `totalTimeFormatted` from the `CleanSum` event of the library, because it only works if you have already run `GetCleanLogs` before running `GetCleanSum`.
https://github.com/mrbungle64/ecovacs-deebot.js/commit/9d1456f885b6cf1b6639447804832f3ecd8c5f54

**Comment by mrbungle64** [comment] 2021-05-15 10:03
@unclej84 

Fixed with latest Github version.

**Closed by mrbungle64** 2021-05-15 10:03 UTC
Labels: Bug (library)
